### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by obsolate** [cosullivan/SmtpServer#112]
Hello, 

We are running the application on kubernetes with the following options. 

var options = new SmtpServerOptionsBuilder()
                .ServerName("SmtpServer InboxSmtpServer")
                .Certificate(CreateCertificate(_hostingEnvironment, _logger))
                .UserAuthenticator(new AuthenticationHandler(....))
                .NetworkBufferReadTimeout(TimeSpan.FromSeconds(100))
                .MessageStore(new MessageGrabber(_cacheManager, _mailManager))
                .Endpoint(builder =>
                    builder
                        .AllowUnsecureAuthentication(true) //false
                        .AuthenticationRequired()
                        .Port(587, true)
                    )
                .Build();

But I think we get the following error when non-secure requesting from load balancer;

Exception:System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
         at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Net.Security.SslState.ThrowIfExceptional()
         at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
         at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
         at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
         at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__50_2(IAsyncResult iar)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at SmtpServer.IO.NetworkClient.UpgradeAsync(X509Certificate certificate, SslProtocols protocols, CancellationToken cancellationToken)
         at SmtpServer.SmtpServer.ListenAsync(IEndpointDefinition endpointDefinition, CancellationToken cancellationToken)
         at SmtpServer.SmtpServer.StartAsync(CancellationToken cancellationToken)

Can you help me?
Thank you.

**Comment by cosullivan** [comment]
Hi,

Is your load balancer handling the TLS, ie, performing any sort of TLS termination? Or is it just passing on the connections to a pool of processes in the cluster?

Thanks,
Cain.

**Comment by obsolate** [comment]
it’s in passthrough mode which only pass the traffic without doing any TLS termination.

**Comment by cosullivan** [comment]
Hi, sorry for the delay in replying. 

The most likely issue could be certificate validation. Are you using a self signed certificate here or have you purchased one?
