### ISSUE TITLE
The SMTP server does not support authentication.

### ISSUE THREAD

**Issue by duyanming** [cosullivan/SmtpServer#154]
System.NotSupportedException
  HResult=0x80131515
  Message=The SMTP server does not support authentication.
  Source=MailKit
  StackTrace:
   at MailKit.Net.Smtp.SmtpClient.<AuthenticateAsync>d__69.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at AnnoStmpServer.SampleMailClient.Send(String from, String to, String subject, String user, String password, MimeEntity body, Int32 count, Boolean useSsl) in D:\project\demo\Experiment\net5\aspnetcore5\AnnoStmpServer\SampleMailClient.cs:line 37
   at AnnoStmpServer.Program.Main(String[] args) in D:\project\demo\Experiment\net5\aspnetcore5\AnnoStmpServer\Program.cs:line 44

  此异常最初是在此调用堆栈中引发的: 
    MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(System.Text.Encoding, System.Net.ICredentials, bool, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    MailKit.Net.Smtp.SmtpClient.Authenticate(System.Text.Encoding, System.Net.ICredentials, System.Threading.CancellationToken)
    MailKit.MailService.Authenticate(System.Text.Encoding, string, string, System.Threading.CancellationToken)
    MailKit.MailService.Authenticate(string, string, System.Threading.CancellationToken)
    AnnoStmpServer.SampleMailClient.Send(string, string, string, string, string, MimeKit.MimeEntity, int, bool) (位于 SampleMailClient.cs 中)
    AnnoStmpServer.Program.Main(string[]) (位于 Program.cs 中)

![image](https://user-images.githubusercontent.com/17999146/109635359-3aa9b780-7b85-11eb-967a-293584d66099.png)

![image](https://user-images.githubusercontent.com/17999146/109635281-25cd2400-7b85-11eb-9ff7-93c7f438c7c6.png)

**Comment by cosullivan** [comment]
You need to also set `AllowUnsecureAuthentication` to true if you aren't using a secure session.

```
var options = new SmtpServerOptionsBuilder()
...
.Endpoint(builder =>
    builder
        .Port(465, false)
        .AllowUnsecureAuthentication(true))
    .Build();
```

**Comment by duyanming** [comment]
thank you
